### ISSUE TITLE
Semantic_linkbacks_type returning incorrectly 

### ISSUE THREAD

**Issue by colin-walker** [pfefferle/wordpress-semantic-linkbacks#82] opened 2017-04-24 16:41 UTC
Issue: the semantic_linkbacks_type function is returning "mention" instead of "like"

Like received here:
https://colinwalker.blog/2017/04/19/sonant-thoughts-episode-11-preparation-and-nerves/

From here:
http://stream.boffosocko.com/2017/liked-colin-walkers-sonant-thoughts-episode-11-preparation-and-nerves

Relevant plugins installed:
IndieWeb
Webmention
Semantic Linkbacks

**Comment by colin-walker** [comment] 2017-04-24 17:16
I currently have the function filtering for "mention" which is why the like shows.

**Comment by miklb** [comment] 2017-04-24 22:50
@colin-walker just to confirm, have you checked to make sure that webmention is indeed stored as a `like`? I've had backfeed from boffosocko come in as only a mention myself, when it was supposed to be a reply. Was mentioned that could be an issue with Known.

**Comment by colin-walker** [comment] 2017-04-25 03:27
@miklb Maybe that's it - it does seem to be stored as mention. If I set my comment walker for a null type then check semantic_linkbacks_type for what's returned it says "mention" rather than like. Didn't know if it was a local issue or not.

**Comment by colin-walker** [comment] 2017-04-25 07:33
After some more testing it does look like this is what's happening. The issue does appear to be with how Known has sent the 'like'.

This can be closed.

**Comment by colin-walker** [comment] 2017-04-25 07:44
Re-opening as requested.

**Comment by miklb** [comment] 2017-04-25 14:19
@colin-walker at leasts it is good to know now that it's how the mention is stored vs the function itself returning improperly.

**Comment by miklb** [comment] 2017-04-25 14:33
per the discussion in #indieweb IRC, a test suite was mentioned later that could be of benefit.

https://github.com/microformats/tests

**Comment by gRegorLove** [comment] 2017-04-25 14:42
The `like-of` property appears to be parsed correctly in @chrisaldrich's post, so I do think this is in one of the WP plugins: http://pin13.net/mf2/?url=http%3A%2F%2Fstream.boffosocko.com%2F2017%2Fliked-colin-walkers-sonant-thoughts-episode-11-preparation-and-nerves

**Comment by pfefferle** [comment] 2017-04-25 15:14
@miklb the test suite does not help here, because the parser has no issues.

@gRegorLove I said parser, but what I meant was interpreter... the parsing is OK, but the `like-of` is in a place where the plugin does not recognize it.

**Comment by snarfed** [comment] 2017-04-30 21:35
subscribing with a vengeance. this has plagued me for years now. can't wait to see it fixed!

examples: https://snarfed.org/2017-03-12_23853#comment-2603533
(both emoji reactions, but i've seen normal replies trigger it too.)

reaction example that didn't trigger it, on the same post: https://snarfed.org/2017-03-12_23853#comment-2603372

IRC discussion: https://chat.indieweb.org/2017-04-30#t1493587145707000

**Comment by chrisaldrich** [comment] 2017-05-03 02:15
@snarfed This may sound crazy, but I used to see something like this issue until I uninstalled the uf2 plugin. I couldn't guarantee it was the cause as I couldn't pin it down exactly, but since uninstalling it, I haven't seen it since. cross reference: https://github.com/pfefferle/wordpress-webmention/issues/97#issuecomment-292746131

**Comment by snarfed** [comment] 2017-05-03 13:56
@chrisaldrich interesting! that would be sad if so. i definitely plan to keep using uf2, so if it's the cause, we should definitely find and fix the bug.

**Comment by pfefferle** [comment] 2017-05-03 14:02
the problem is that I no longer selfdogfooding the uf2 plugin, but I am open to add new contributors.

**Comment by dshanske** [comment] 2017-05-10 04:42
Should be addressed by #85

**Comment by dshanske** [comment] 2017-06-03 23:54
Believe this can be closed now with latest merge.

**Comment by pfefferle** [comment] 2017-06-04 06:53
@colin-walker can you verify this?

**Comment by colin-walker** [comment] 2017-06-05 07:50
Will keep an eye on it and let you know.

**Comment by dshanske** [comment] 2017-11-27 16:06
Poke?

**Comment by snarfed** [comment] 2017-11-27 16:44
i haven't seen this for a while. I'm ok with closing.

**Closed** 2017-11-27 17:14 UTC
